### ISSUE TITLE
Win32Exception

### ISSUE THREAD

**Issue by Matt4499** [Tyrrrz/YoutubeExplode.Converter#16]
System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=The system cannot find the file specified
  Source=System
  StackTrace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CliWrap.Internal.CliProcess.Start()
   at CliWrap.Cli.StartProcess()
   at CliWrap.Cli.<ExecuteAsync>d__30.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at YoutubeExplode.Converter.YoutubeConverter.<DownloadAndProcessMediaStreamsAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at mPlayer.MusicDownload.<MaterialFlatButton1_Click>d__2.MoveNext() in C:\Users\Matt\source\repos\mPlayer\MusicDownload.cs:line 68

CODE:
```
    var client = new YoutubeClient();
            var converter = new YoutubeConverter();
            string link = SearchBoxInput.Text;
            string id = YoutubeClient.ParseVideoId(link);
            var video = await client.GetVideoAsync(id);

            var streamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);
            var audioStreamInfo = streamInfoSet.Audio.WithHighestBitrate();


            var mediaStreamInfos = new MediaStreamInfo[] { audioStreamInfo };


            var title = video.Title;

            await converter.DownloadAndProcessMediaStreamsAsync(mediaStreamInfos, title + ".mp3", "mp3");
```

**Comment by Tyrrrz** [comment]
#12?

**Comment by Tyrrrz** [comment]
Have you managed to fix this?

**Comment by Matt4499** [comment]
I haven't fixed this specifically, but basically made it just download the whole ass video, then using nreco.videoconverter to convert to mp3, then delete the mp4 left behind

**Comment by Tyrrrz** [comment]
Did you have ffmpeg in your working directory?

**Comment by Matt4499** [comment]
Yes

Sent from my iPhone

On Aug 29, 2019, at 3:33 PM, Alexey Golub <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you have ffmpeg in your working directory?
