### ISSUE TITLE
No process is associated with this object when combining streams

### ISSUE THREAD

**Issue by itsliamprowse** [Tyrrrz/YoutubeExplode.Converter#25]
When downloading video and audio separately, i can see both files get created in the filesystem correctly, however then the DownloadAndProcessMediaStreamsAsync method throws a System.InvalidOperationException: 'No process is associated with this object.'

System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at CliWrap.Internal.ProcessEx.Dispose()
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken cancellationToken)
   at YoutubeExplode.Converter.Internal.FFmpeg.ConvertAsync(String outputFilePath, IReadOnlyList`1 inputFilePaths, String format, String preset, Boolean avoidTranscoding, IProgress`1 progress, CancellationToken cancellationToken)
   at YoutubeExplode.Converter.YoutubeConverter.DownloadAndProcessMediaStreamsAsync(IReadOnlyList`1 streamInfos, String filePath, String format, ConversionPreset preset, IProgress`1 progress, CancellationToken cancellationToken)

This only started happening in the past few days, nothing has changed, we haven't touched our code since it was last working, videos that worked a few days ago do not work today

**Comment by Tyrrrz** [comment]
Hi.
Does it happen all the time or sporadically?
Does `ffmpeg.exe` exist in the working directory?

**Comment by itsliamprowse** [comment]
huh strange, i deleted the exe and recopied it in and its working now
Thanks :D

**Comment by Tyrrrz** [comment]
Hm. Did you notice if the file was corrupted or anything? Really curious why that could be happening.

**Comment by itsliamprowse** [comment]
Not that I noticed no, its possible though

**Comment by Tyrrrz** [comment]
Okay. Good thing it works now, I guess.

**Comment by LinuxDoku** [comment]
FYI, we had the same exception. In our case the binary had no execute permission in the docker container. Adding `RUN chmod +x some-binary` fixed it.
