### ISSUE TITLE
"The system cannot find the file specified"

### ISSUE THREAD

**Issue by JohnKlineKurtz** [Tyrrrz/YoutubeExplode.Converter#30]
When performing a join with a 1080p mp4 video and another audio mp4 stream, the video downloads into the first tmp file and then (I assume) the audio downloads into the second tmp file, but after that they both dissappear , I get the following error:

"The system cannot find the file specified"

For an example, I am trying to join Video ID of oyA7Ucnmje4

I see this file first:
"360hometours.ca - Grand Home Design _ Modern Architecture _ Vancouver [1080p].mp4.stream-1.tmp"
Then for a split second I see this one:
"360hometours.ca - Grand Home Design _ Modern Architecture _ Vancouver [1080p].mp4.stream-2.tmp"
Then it gives the exception.
Both files disappear.

Here is my code:
                            var ytClient = new YoutubeClient();
                            IProgress<double> idblProgress = new Progress<double>(ReportProgress);
                            List<YoutubeExplode.Videos.Streams.IStreamInfo> lMSI = new List<YoutubeExplode.Videos.Streams.IStreamInfo>();
                            lMSI.Add(_VideoStreamInfo);
                            lMSI.Add(_AudioStreamInfo);
                            _Status = YouTubeDownloadStatus.Fetching;
                            ConversionRequest CR = new ConversionRequestBuilder(sPathAndFile).Build();
                            await ytClient.Videos.DownloadAsync(lMSI, CR, idblProgress, _CT);

Here is the stack trace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at CliWrap.Internal.ProcessEx.Start()
   at CliWrap.Command.<ExecuteAsync>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Converter.FFmpeg.<ExecuteAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Converter.ConversionExtensions.<DownloadAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at YTFetch.ucYouTubeFetch.<ucYouTubeDownload_Load>d__34.MoveNext() in C:\Projects\YTFetch\YTFetch\ucYouTubeFetch.cs:line 226

I am trying to save to location:
C:\External\D1\Media\Video\Work\Data\Joined\360hometours.ca - Grand Home Design _ Modern Architecture _ Vancouver [1080p].mp4

I upgraded your projects to the latest stable version.

Also, I can just do the video download and it works, so something in the join is failing.

**Comment by Tyrrrz** [comment]
Hi.

The temporary files disappear in the end regardless of success or failure because they are cleaned up.

Your problem is that it cannot find FFmpeg on the path or in the immediate directory. If it's somewhere else you may want to use `.SetFFmpegPath()` to tell the library about it.

**Comment by JohnKlineKurtz** [comment]
Thank you Alexey. I will give it a try tonight... makes sense now that I think about what I was seeing.

**Comment by JohnKlineKurtz** [comment]
That worked! Thanks... For others who may need it, .SetFFmpegPath is now a parameter in new ConversionRequest(...) but not in the ConversionRequestBuilder.
