### ISSUE TITLE
CliWrap.Exceptions.CommandExecutionException: 'Underlying process reported a non-zero exit code (-1073741819)

### ISSUE THREAD

**Issue by jaywebster18** [Tyrrrz/YoutubeExplode.Converter#32]
This video downloads to about 20% and then always gives me the following exception:
```
CliWrap.Exceptions.CommandExecutionException: 'Underlying process reported a non-zero exit code (-1073741819).
This exception was originally thrown at this call stack:
    CliWrap.Command.ExecuteAsync(CliWrap.Internal.ProcessEx, System.Threading.CancellationToken)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    YoutubeExplode.Converter.FFmpeg.ExecuteAsync(System.Collections.Generic.IReadOnlyList<string>, string, string, string, bool, System.IProgress<double>, System.Threading.CancellationToken)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
    YoutubeExplode.Converter.ConversionExtensions.DownloadAsync(YoutubeExplode.Videos.VideoClient, System.Collections.Generic.IReadOnlyList<YoutubeExplode.Videos.Streams.IStreamInfo>, YoutubeExplode.Converter.ConversionRequest, System.IProgress<double>, System.Threading.CancellationToken)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
```

The video id is:
lDK9QqIzhwk

YoutubeExplode v5.1.8 / YoutubeExplode.Converter v2.0.0

**Comment by Tyrrrz** [comment]
Can you...

1. Clone this repo

2. Change `ExecuteAsync()` to `ExecuteBufferedAsync()` on [this line](https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/db350e0a99ad8eca55c0df99fe30c149facabe14/YoutubeExplode.Converter/FFmpeg.cs#L81) (will have to add `using CliWrap.Buffered;` at the top)

3. Change one of the tests to use your video, for example [here](https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/db350e0a99ad8eca55c0df99fe30c149facabe14/YoutubeExplode.Converter.Tests/GeneralSpecs.cs#L36)

4. Run the test

This should give a bit more information on the error

**Comment by jaywebster18** [comment]
Thanks for the quick response.

I had it set to download at the highest quality which in this case is 2160p, I amended the code to download in 1080p and it downloaded fine, so looks like it has something to do with that.

**Updated Exception Error below:**
```
CliWrap.Exceptions.CommandExecutionException
  HResult=0x80131500
  Message=Underlying process reported a non-zero exit code (-1073741819).

Command:
  C:\Users\jaywe\Desktop\YoutubeExplode-master\YoutubeExplode.DemoConsole\bin\Debug\netcoreapp3.1\ffmpeg.exe -i "C:\Users\jaywe\Documents\YoutubeVideos\Music Videos\Bon Jovi\Bon Jovi - LOAP.mp4.stream-1.tmp" -i "C:\Users\jaywe\Documents\YoutubeVideos\Music Videos\Bon Jovi\Bon Jovi - LOAP.mp4.stream-2.tmp" -f mp4 -preset medium -threads 4 -nostdin -shortest -y "C:\Users\jaywe\Documents\YoutubeVideos\Music Videos\Bon Jovi\Bon Jovi - LOAP.mp4"

Standard error:
  ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'C:\Users\jaywe\Documents\YoutubeVideos\Music Videos\Bon Jovi\Bon Jovi - LOAP.mp4.stream-1.tmp':
  Metadata:
    encoder         : google/video-file
  Duration: 00:04:08.82, start: -0.007000, bitrate: 126 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[libaom-av1 @ 068d4f00] 1.0.0-2379-g861fd02c8
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\jaywe\Documents\YoutubeVideos\Music Videos\Bon Jovi\Bon Jovi - LOAP.mp4.stream-2.tmp':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6av01mp41
    creation_time   : 2020-10-18T04:11:05.000000Z
  Duration: 00:04:08.80, start: 0.000000, bitrate: 10553 kb/s
    Stream #1:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 3840x2160, 54 kb/s, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      creation_time   : 2020-10-18T04:11:05.000000Z
      handler_name    : ISO Media file produced by Google Inc.
[libaom-av1 @ 06901f40] 1.0.0-2379-g861fd02c8
Stream mapping:
  Stream #1:0 -> #0:0 (av1 (libaom-av1) -> h264 (libx264))
  Stream #0:0 -> #0:1 (opus (native) -> aac (native))

You can suppress this validation by calling `WithValidation(CommandResultValidation.None)` on the command.
  Source=CliWrap
  StackTrace:
   at CliWrap.Buffered.BufferedCommandExtensions.<>c__DisplayClass0_0.<ExecuteBufferedAsync>b__0(CommandResult r)
   at CliWrap.Internal.Extensions.AsyncExtensions.<Select>d__0`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at YoutubeExplode.Converter.FFmpeg.<ExecuteAsync>d__3.MoveNext() in C:\Users\jaywe\Desktop\YoutubeExplode.Converter-master\YoutubeExplode.Converter\FFmpeg.cs:line 79
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeExplode.Converter.ConversionExtensions.<DownloadAsync>d__2.MoveNext() in C:\Users\jaywe\Desktop\YoutubeExplode.Converter-master\YoutubeExplode.Converter\ConversionExtensions.cs:line 111
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeVideos.Program.<DownloadVideos>d__14.MoveNext() in C:\Users\jaywe\Desktop\YoutubeExplode-master\YoutubeExplode.DemoConsole\Program.cs:line 218
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YoutubeVideos.Program.<MenuAsync>d__10.MoveNext() in C:\Users\jaywe\Desktop\YoutubeExplode-master\YoutubeExplode.DemoConsole\Program.cs:line 80
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YoutubeVideos.Program.<Main>d__8.MoveNext() in C:\Users\jaywe\Desktop\YoutubeExplode-master\YoutubeExplode.DemoConsole\Program.cs:line 28
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at YoutubeVideos.Program.<Main>()

  This exception was originally thrown at this call stack:
    CliWrap.Buffered.BufferedCommandExtensions.ExecuteBufferedAsync.AnonymousMethod__0(CliWrap.CommandResult)
    CliWrap.Internal.Extensions.AsyncExtensions.Select<TSource, TDestination>(System.Threading.Tasks.Task<TSource>, System.Func<TSource, TDestination>)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
    YoutubeExplode.Converter.FFmpeg.ExecuteAsync(System.Collections.Generic.IReadOnlyList<string>, string, string, string, bool, System.IProgress<double>, System.Threading.CancellationToken) in FFmpeg.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    ...
    [Call Stack Truncated]
```

**Comment by jaywebster18** [comment]
I think i worked it out. I assume you can only download 2160p video in webm format and not mp4?

**THIS DOES NOT WORK**
`var videoStreamInfo = streamManifest.GetVideoOnly().Where(s => s.Container == Container.Mp4).WithHighestVideoQuality();`

**THIS WORKS**
`var videoStreamInfo = streamManifest.GetVideoOnly().FirstOrDefault(s => s.VideoQualityLabel == "1080p");`

**THIS WORKS**
`var videoStreamInfo = streamManifest.GetVideoOnly().WithHighestVideoQuality();`

**THIS WORKS**
var videoStreamInfo = streamManifest.GetVideoOnly().Where(s => s.Container == Container.Mp4).FirstOrDefault(s => s.VideoQualityLabel == "1080p");

**Comment by Tyrrrz** [comment]
So there is nothing in the stderr and it appears that `-1073741819` corresponds to access violation. In other words, something failed in FFmpeg and caused it to crash.

**Comment by Tyrrrz** [comment]
>  I assume you can only download 2160p video in webm format and not mp4?

I don't think `mp4` ever comes in 2160p. Are you passing `null`s into `DownloadVideoAsync()`?

**Comment by jaywebster18** [comment]
could that not be the issue then, i am trying to download 2160p as mp4 and its failing? it seems to work under all other scenarios.

Nope, no null, I use the below:

var streamInfos = new IStreamInfo[] { audioStreamInfo, videoStreamInfo };
using (var progress = new InlineProgress())
	await youtube.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder($@"{DownloadPath}{video[2]}\{video[2]} - {video[3]}.mp4").Build(), progress);

**Comment by Tyrrrz** [comment]
I mean, are `audioStreamInfo` and `videoStreamInfo` also not null? Because `WithHighestVideoQuality()` may return `null` if the sequence is empty.

**Comment by jaywebster18** [comment]
Ah, i see. 

Just checked audioStreamInfo and videoStreamInfo and both are not null

**Comment by Tyrrrz** [comment]
Hm, very interesting. In that case I have no idea what goes wrong and unfortunately FFmpeg doesn't provide any clues :/

**Comment by jaywebster18** [comment]
ok, i will just work around it.

Thanks for looking into it :)

**Comment by Tyrrrz** [comment]
Closing this issue pending a merger with the main repository. Will reopen there once it's complete.
